### ISSUE TITLE
Cube files rendering tool.

### ISSUE THREAD

**Issue by yakutovicha** [nanotech-empa/general-issues#4]
TODO:

- [ ] Investigate available solutions.
- [ ] Decide which option to take.

**Comment by yakutovicha** [comment]
Available solutions:
- Render with VMD. Explained [here](https://psicode.org/psi4manual/1.5.0/cubeprop.html) and implemented [here](https://github.com/psi4/psi4/blob/master/psi4/share/psi4/scripts/vmd_cube.py).
- Render with [pymol](https://pymolwiki.org/index.php/Jupyter). See our [current implementation](https://github.com/nanotech-empa/aiida-nanotech-empa/blob/056bea58c58250f8cb50a30cbedd44ca89a49c9c/aiida_nanotech_empa/utils/pymol_render.py) that is failing from time to time.
- Render with [povray](http://www.povray.org/) using [vapory](https://github.com/Zulko/vapory). 
- Render with [Fresnel](https://fresnel.readthedocs.io/en/stable/)
- Render with [ASE](https://wiki.fysik.dtu.dk/ase/_modules/ase/visualize/mlab.html#plot) using [myavi](https://docs.enthought.com/mayavi/mayavi/).
- Render with [beautiful atoms](https://beautiful-atoms.readthedocs.io/en/latest/tutorial/volumetric.html) that employs [Blender](https://www.blender.org/) as a rendering engine

**Comment by yakutovicha** [comment]
Trying to run the ASE solution, which seemed to be the simplest one, immediately resulted in an error, when trying to import `mlab`.

```python
Traceback (most recent call last):
  File "mlab.py", line 136, in <module>
    main()
  File "mlab.py", line 132, in main
    plot(atoms, data, contours)
  File "mlab.py", line 26, in plot
    from mayavi import mlab
  File "/Users/yakutovicha/anaconda3/lib/python3.7/site-packages/mayavi/mlab.py", line 16, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "/Users/yakutovicha/anaconda3/lib/python3.7/site-packages/mayavi/tools/camera.py", line 24, in <module>
    from .engine_manager import get_engine
  File "/Users/yakutovicha/anaconda3/lib/python3.7/site-packages/mayavi/tools/engine_manager.py", line 15, in <module>
    from mayavi.core.engine import Engine
  File "/Users/yakutovicha/anaconda3/lib/python3.7/site-packages/mayavi/core/engine.py", line 28, in <module>
    from mayavi.core.scene import Scene
  File "/Users/yakutovicha/anaconda3/lib/python3.7/site-packages/mayavi/core/scene.py", line 15, in <module>
    from mayavi.core.source import Source
  File "/Users/yakutovicha/anaconda3/lib/python3.7/site-packages/mayavi/core/source.py", line 23, in <module>
    from mayavi.core.adder_node import ModuleFilterAdderNode
  File "/Users/yakutovicha/anaconda3/lib/python3.7/site-packages/mayavi/core/adder_node.py", line 16, in <module>
    from pyface.api import ImageResource
  File "/Users/yakutovicha/anaconda3/lib/python3.7/site-packages/pyface/api.py", line 105, in <module>
    from .about_dialog import AboutDialog
  File "/Users/yakutovicha/anaconda3/lib/python3.7/site-packages/pyface/about_dialog.py", line 17, in <module>
    AboutDialog = toolkit_object("about_dialog:AboutDialog")
  File "/Users/yakutovicha/anaconda3/lib/python3.7/site-packages/pyface/base_toolkit.py", line 127, in __call__
    module = import_module(mname, package)
  File "/Users/yakutovicha/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/yakutovicha/anaconda3/lib/python3.7/site-packages/pyface/ui/qt4/about_dialog.py", line 19, in <module>
    from .dialog import Dialog
  File "/Users/yakutovicha/anaconda3/lib/python3.7/site-packages/pyface/ui/qt4/dialog.py", line 29, in <module>
    int(QtGui.QDialog.DialogCode.Accepted): OK,
AttributeError: type object 'DialogCode' has no attribute 'Accepted'
```

I also tried to downgrade the version of myavi, but I always got an issue:
```python
      Current thread 0x0000000104415dc0 (most recent call first):
        File "/private/var/folders/6g/_qx7vshn15gb1p7dhjtpby580000gn/T/pip-install-ovi0f27q/mayavi_0c2e6237dfab4c8eaa807aa284887c3d/tvtk/vtk_parser.py", line 705 in _find_get_set_methods
        File "/private/var/folders/6g/_qx7vshn15gb1p7dhjtpby580000gn/T/pip-install-ovi0f27q/mayavi_0c2e6237dfab4c8eaa807aa284887c3d/tvtk/vtk_parser.py", line 488 in _organize_methods
        File "/private/var/folders/6g/_qx7vshn15gb1p7dhjtpby580000gn/T/pip-install-ovi0f27q/mayavi_0c2e6237dfab4c8eaa807aa284887c3d/tvtk/vtk_parser.py", line 154 in parse
        File "/private/var/folders/6g/_qx7vshn15gb1p7dhjtpby580000gn/T/pip-install-ovi0f27q/mayavi_0c2e6237dfab4c8eaa807aa284887c3d/tvtk/wrapper_gen.py", line 341 in _gen_methods
        File "/private/var/folders/6g/_qx7vshn15gb1p7dhjtpby580000gn/T/pip-install-ovi0f27q/mayavi_0c2e6237dfab4c8eaa807aa284887c3d/tvtk/wrapper_gen.py", line 242 in generate_code
        File "/private/var/folders/6g/_qx7vshn15gb1p7dhjtpby580000gn/T/pip-install-ovi0f27q/mayavi_0c2e6237dfab4c8eaa807aa284887c3d/tvtk/code_gen.py", line 235 in _write_wrapper_class
        File "/private/var/folders/6g/_qx7vshn15gb1p7dhjtpby580000gn/T/pip-install-ovi0f27q/mayavi_0c2e6237dfab4c8eaa807aa284887c3d/tvtk/code_gen.py", line 142 in generate_code
        File "tvtk/setup.py", line 98 in gen_tvtk_classes_zip
        File "/private/var/folders/6g/_qx7vshn15gb1p7dhjtpby580000gn/T/pip-install-ovi0f27q/mayavi_0c2e6237dfab4c8eaa807aa284887c3d/setup.py", line 254 in build_tvtk_classes_zip
        File "/private/var/folders/6g/_qx7vshn15gb1p7dhjtpby580000gn/T/pip-install-ovi0f27q/mayavi_0c2e6237dfab4c8eaa807aa284887c3d/setup.py", line 268 in run
        File "/Users/yakutovicha/anaconda3/lib/python3.7/distutils/dist.py", line 985 in run_command
        File "/Users/yakutovicha/anaconda3/lib/python3.7/distutils/cmd.py", line 313 in run_command
        File "/Users/yakutovicha/anaconda3/lib/python3.7/distutils/command/install.py", line 545 in run
        File "/Users/yakutovicha/anaconda3/lib/python3.7/site-packages/numpy/distutils/command/install.py", line 34 in setuptools_run
        File "/Users/yakutovicha/anaconda3/lib/python3.7/site-packages/numpy/distutils/command/install.py", line 60 in run
        File "/Users/yakutovicha/anaconda3/lib/python3.7/distutils/dist.py", line 985 in run_command
        File "/Users/yakutovicha/anaconda3/lib/python3.7/distutils/dist.py", line 966 in run_commands
        File "/Users/yakutovicha/anaconda3/lib/python3.7/distutils/core.py", line 148 in setup
        File "/Users/yakutovicha/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145 in setup
        File "/Users/yakutovicha/anaconda3/lib/python3.7/site-packages/numpy/distutils/core.py", line 169 in setup
        File "/private/var/folders/6g/_qx7vshn15gb1p7dhjtpby580000gn/T/pip-install-ovi0f27q/mayavi_0c2e6237dfab4c8eaa807aa284887c3d/setup.py", line 464 in <module>
        File "<pip-setuptools-caller>", line 34 in <module>
        File "<string>", line 36 in <module>
      [end of output]
```

**Comment by yakutovicha** [comment]
Render with VMD using this [python file](https://github.com/psi4/psi4/blob/master/psi4/share/psi4/scripts/vmd_cube.py) went smoothly:

```bash
$ python vmd_cube.py --iso 0.2 --opacity 0.6 cubefile_dir/

Parameters:
  Cubefile Directory   cubefile_dir/
  Font size            20
  Gzip Cube Files      False
  Image height         250
  Image width          250
  Interactive Mode     False
  Isosurface1 Value    0.2
  Isosurface2 Value    -0.2
  Label MOs            True
  Montage              True
  Opacity              0.6
  X-axis Rotation      30.0
  Y-axis Rotation      40.0
  Z-axis Rotation      15.0
  Scaling Factor       1.0
  Surface1 Color Id    3
  Surface2 Color Id    23
  X-axis Translation   0.0
  Y-axis Translation   0.0
  Z-axis Translation   0.0
  VMD Path             /apps/daint/UES/jenkins/7.0.UP03/21.09/daint-gpu/software/VMD/1.9.4a54/bin/vmd
```

![5_a_homo](https://user-images.githubusercontent.com/13118485/200329762-d9b33841-1d44-49d8-a0f8-d618138b264a.png)

**Comment by yakutovicha** [comment]
What concerns Pymol: we use it for our rendering, but the setup is a bit convoluted as it has a lot of non-python dependencies:

```bash
# For Ubuntu
sudo apt install git build-essential python3-dev libglew-dev libpng-dev libfreetype6-dev libxml2-dev libmsgpack-dev python3-pyqt5.qtopengl libglm-dev libnetcdf-dev

cd ~/opt/
git clone https://github.com/schrodinger/pymol-open-source.git
cd pymol-open-source
python setup.py install
```

At the same time the Python interface is quite unreliable. Pymol sometimes creates the png with a delay and sometimes even after a long delay, the image is not created. We had to add a workaround below, which still doesn't work in all cases:

```python
    for _try in range(2):
        # if the image is not created, try to create it again (loop over _try)
        cmd.png(fname, width=f"{max_w + 1}cm", dpi=500, ray=1)
        # Wait for a bit
        for _i in range(200):
            if os.path.isfile(fname):
                break
            time.sleep(0.5)
        if os.path.isfile(fname):
            break
```

**Comment by cpignedoli** [comment]
Pros and cons

- VMD-based solution: robust, most of us are quite familiar with VMD, it is already installed at CSCS, could appear as slightly obsolete
- pymol for me is a NO-GO it is not reliable we already wasted too much time on it
- povray, I consider it not straightforward, and CPU consuming. Excellent image quality
- blender based, I would go for this if it is clear that we can use it without GUI on e.g. daint as it is for VMD. cons: will they support future versions of blender?
- myavi, I am waiting for a working example. Seems to me a little bit of an overshooting.
- Fresnel: does anybody have working examples for our cases?

**Comment by yakutovicha** [comment]
With beautiful atoms, we could generate the following image:
![h2o-homo](https://user-images.githubusercontent.com/13118485/201967921-595dfde8-f537-4752-b764-b52645b8e02a.png)

In principle, this is an interesting approach: it enables beautiful atoms extension for Blender. I managed to install Blender on a supercomputer. 

The simulation script used to generate the image is the following:

```python
from ase.io.cube import read_cube_data
from batoms import Batoms
volumetric_data, atoms = read_cube_data("datas/h2o-homo.cube")
h2o = Batoms('h2o', from_ase = atoms)
# add volumetric data
h2o.volumetric_data['homo'] = volumetric_data
h2o.isosurface.setting[1] = {"level": 0.002, }
h2o.isosurface.setting[2] = {"level": -0.002, "color": [0, 0, 0.8, 0.5]}
h2o.isosurface.draw()
h2o.get_image(viewport = [0, 0 ,1], engine = "cycles", output = "h2o-homo.png")
```

**Comment by cpignedoli** [comment]
**Update after discussion with Giovanni** 

The target applications in order of complexity are the following:
A workchain produces one or more cube files (charge density, spin density, KS orbitals, STS (cube where z axis is energy)
AiiDA retrieves and keeps the minimal accuracy version of the cube files
In apps the user promply visualizes low quality 3D or 2D images, and can then ask to produce a High quality image that will be stored in AiiDA.
The High quality requires the full size cube file to be still available either stashed or on the scratch.
 
**Target Apps:**

-Associated to a geometry I have a viewer of the charge density
-Associated to.a GEO I have the viz for spin density
-Associated to a GEO, viz of charge density difference
-Associated to a Geo and Bandstructure I can decide to plot for kpt1,kpt5,kpt10,… for band VBM, VBM-1,VBM-2, CBm, CBM+1,… the KS orbitals
They will then be available easily reachable from the bands. If after few months I decide I need additonla KS that were not computed, a new calculation will start and the list of available states will be updated so that still from the bands I have full control over what is available
-Associated to bands or molecules, viz of 2D STS map (superposition of KS orbitals at different energies with G broadening around a selected energy (a cube file with energy in Z)

**PROBLEM:** we have a large cube file (~400MB). We want to give quick visual inspection,
also of something lower res, but that works with live interaction to rotate, choose
isosurface etc. so a AiiDAlab user can decide a list of camera directions and isosurfaces by
visual inspection, add them to a list of tasks with a button, and then ask a slow high-quality
render of the whole list.

**The idea:** downsample (and use a few more tricks) to send to the GUI a much smaller file, let the
user select the list of renders, then execute the render on the full file.
Some size and quality benchmarking below:
Full cube file: 414MB
Full cube file (GZIPPED): 127MB
Reducing by [::6, ::6, ::6] is too much
Reducing by [::4, ::4, ::4] is ok for quick viz, also with various isovalues, even if not perfect, but
good compromise. The grid density is ~1 bohr, so ~0.53 Ångstrom. One should target this density.
Reduced 4x4x4: 6.7MB
Reduced 4x4x4, and trimmed printing using %.3f (remembrer to do it after dividing by
max(abs(data.min()), abs(data.max()) to normalize values: 3.2MB
Further converting values “-0.000” and “0.000” to “0”: 1.6MB
(Gzipping gives 187KB!!)
see screenshots
Python code:
```python
import ase, ase.io
grid, asecell = ase.io.cube.read_cube_data(‘spin.cube')
reduced_grid = grid[::4, ::4, ::4]
with open('reduced-spin.cube', 'w') as fh:
ase.io.cube.write_cube(fh, asecell, reduced_grid)
```
To use a different format, copy the source of write_cube and change format in the very last line
from %e to %.3f
To trim, you can use a regexp, I used (in VS Code) a replace:
^-0\.000
to
0
FOLLOWED by
^0\.000
to
0
(can be done all in python of course)
Note: The isosurface from the reduced cube, rendered in .obj becomes bigger: 50MB as the
renderer tries still to keep a large number of triangles, even if the underlying mesh is coarse. With
the full mesh, it was 200MB. Since in this case one would need to create many obj files for
various isosurface values (let’s say at leat 5-10), this approach does not seem interesting (and is
actually more complex)



![Image](https://github.com/nanotech-empa/general-issues/assets/22955065/950aebcf-4879-4445-aaa1-f326767ba361)
